name: Trigger build of base-image

# Configures this workflow to run every time a change is pushed to the branch called `main`.
on:
  workflow_dispatch:

# The GitHub CLI needs acces to the `github.token`
env:
    GH_TOKEN: ${{ github.token }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  trigger-build-of-base-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions: write-all
    steps:
      - name: Trigger build
        run: "gh api --method POST -H \"Accept: application/vnd.github+json\" -H \"X-GitHub-Api-Version: 2022-11-28\" /repos/fermentatiekast/base-image/actions/workflows/140076487/dispatches -f \"ref=main\""
