name: Trigger build of base-image

# Configures this workflow to run every time a change is pushed to the branch called `main`.
on:
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  trigger-build-of-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: "gh workflow run --repo fermentatiekast/base-image 140076487"
